import { Noto_Sans_Arabic, Poppins } from "next/font/google"
import { getLocalePartsFrom, locales } from "@/middleware";
import Navbar from "./components/Navbar/Navbar";
import "react-big-calendar/lib/css/react-big-calendar.css"
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ["latin"]
})

/*
const NotoSansArabic = Noto_Sans_Arabic({
  weight: ['400', '700'],
  subsets: ["arabic"]
})
*/

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
    return locales.map((locale) => getLocalePartsFrom({ locale }));
  }

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  return (
    <html dir="ltr">
      <body data-theme="dark-theme" className={ poppins.className }>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
